[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
startCommand = "python src/mlops_rec_sys/server.py"

[variables]
PORT = "50051"
PYTHON_VERSION = "3.13.0"